import { Project, CalendarEvent, Task, TeamMember, ProjectId } from './types'

// Week anchor: Monday 2026-05-04
const WEEK_START = '2026-05-04'

function weekDay(offsetDays: number): string {
  const d = new Date(WEEK_START)
  d.setDate(d.getDate() + offsetDays)
  return d.toISOString().split('T')[0]
}

const MON = weekDay(0) // 2026-05-04
const TUE = weekDay(1)
const WED = weekDay(2)
const THU = weekDay(3)
const FRI = weekDay(4)
const SAT = weekDay(5)
const SUN = weekDay(6)

// ─── Projects ───────────────────────────────────────────────────────────────

export const PROJECTS: Project[] = [
  {
    id: 'general',
    name: 'General Studio',
    color: '#7c3aed',
    accentClass: 'bg-purple-600',
    borderClass: 'border-purple-500',
    bgClass: 'bg-purple-50',
    textClass: 'text-purple-700',
    memberCount: 8,
    description: 'Cross-project tasks, studio-wide meetings, and admin',
  },
  {
    id: 'lastlight',
    name: 'Last Light',
    color: '#0d9488',
    accentClass: 'bg-teal-600',
    borderClass: 'border-teal-500',
    bgClass: 'bg-teal-50',
    textClass: 'text-teal-700',
    memberCount: 10,
    description: 'Atmospheric narrative puzzle game',
  },
  {
    id: 'corebound',
    name: 'Corebound',
    color: '#2563eb',
    accentClass: 'bg-blue-600',
    borderClass: 'border-blue-500',
    bgClass: 'bg-blue-50',
    textClass: 'text-blue-700',
    memberCount: 9,
    description: 'Action-RPG with procedural dungeon systems',
  },
  {
    id: 'bigboss',
    name: 'Big Boss Cleanup',
    color: '#d97706',
    accentClass: 'bg-amber-600',
    borderClass: 'border-amber-500',
    bgClass: 'bg-amber-50',
    textClass: 'text-amber-700',
    memberCount: 8,
    description: 'Final polish & QA pass on legacy title',
  },
]

// ─── Team Members (real Kato.8 Studios roster) ───────────────────────────────

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'terry',
    name: 'Terry Teng',
    role: 'Founder & CEO',
    avatar: '',
    initials: 'TT',
    projects: ['general', 'lastlight', 'corebound', 'bigboss'],
    noMeetingDays: ['Tue'],
    focusHours: '9am–12pm',
    timezone: 'PST',
  },
  {
    id: 'ryan-k',
    name: 'Ryan Kenfield',
    role: 'Lead Game Designer',
    avatar: '',
    initials: 'RK',
    projects: ['general', 'lastlight'],
    noMeetingDays: ['Fri', 'Sat', 'Sun'],
    focusHours: 'Flexible',
    timezone: 'MST',
  },
  {
    id: 'pride',
    name: 'Pride St. Clair',
    role: 'Lead Game Designer',
    avatar: '',
    initials: 'PC',
    projects: ['general', 'corebound'],
    noMeetingDays: [],
    focusHours: 'Mon–Fri',
    timezone: 'PST',
  },
  {
    id: 'bryan',
    name: 'Bryan N',
    role: 'Lead Artist',
    avatar: '',
    initials: 'BN',
    projects: ['general', 'lastlight'],
    noMeetingDays: [],
    focusHours: 'Flexible',
    timezone: 'PST',
  },
  {
    id: 'hailey',
    name: 'Hailey Hebden',
    role: 'Lead Artist',
    avatar: '',
    initials: 'HH',
    projects: ['general', 'corebound'],
    noMeetingDays: [],
    focusHours: 'After 5PM or Mon/Tue after 10AM',
    timezone: 'EST',
  },
  {
    id: 'carlos',
    name: 'Carlos Trujillo',
    role: 'Lead Engineer',
    avatar: '',
    initials: 'CT',
    projects: ['general', 'lastlight'],
    noMeetingDays: [],
    focusHours: 'Flexible',
    timezone: 'PST',
  },
  {
    id: 'rhianna',
    name: 'Rhianna Pinkerton',
    role: 'Lead Engineer',
    avatar: '',
    initials: 'RH',
    projects: ['general', 'corebound'],
    noMeetingDays: [],
    focusHours: 'Flexible',
    timezone: 'PST',
  },
  {
    id: 'daniel',
    name: 'Daniel Fornell',
    role: 'Unreal Developer',
    avatar: '',
    initials: 'DF',
    projects: ['general', 'bigboss'],
    noMeetingDays: ['Sun'],
    focusHours: 'Post 1:30PM EST',
    timezone: 'EST',
  },
  {
    id: 'tessa',
    name: 'Tessa Lee',
    role: 'UI/UX Lead',
    avatar: '',
    initials: 'TL',
    projects: ['general', 'lastlight', 'corebound'],
    noMeetingDays: ['Mon', 'Tue', 'Wed', 'Thu'],
    focusHours: 'Fridays / weekends',
    timezone: 'EST',
  },
  {
    id: 'sophia',
    name: 'Sophia J',
    role: 'Lead Game Designer',
    avatar: '',
    initials: 'SJ',
    projects: ['general', 'bigboss'],
    noMeetingDays: [],
    focusHours: 'Weekdays before 9:30–10AM PST',
    timezone: 'PST',
  },
]

// ─── Calendar Events ─────────────────────────────────────────────────────────

export const CALENDAR_EVENTS: CalendarEvent[] = [
  // General Studio – recurring studio standup Mon/Wed/Fri
  {
    id: 'ev-001',
    projectId: 'general',
    title: 'Studio Standup',
    type: 'standup',
    date: MON,
    startTime: '10:00',
    endTime: '10:20',
    attendees: ['Terry Teng', 'Ryan Kenfield', 'Pride St. Clair', 'Bryan N', 'Sophia J', 'Rhianna Pinkerton'],
    isRecurring: true,
  },
  {
    id: 'ev-002',
    projectId: 'general',
    title: 'Studio Standup',
    type: 'standup',
    date: WED,
    startTime: '10:00',
    endTime: '10:20',
    attendees: ['Terry Teng', 'Ryan Kenfield', 'Pride St. Clair', 'Bryan N', 'Sophia J', 'Rhianna Pinkerton'],
    isRecurring: true,
  },
  {
    id: 'ev-003',
    projectId: 'general',
    title: 'Studio Standup',
    type: 'standup',
    date: FRI,
    startTime: '10:00',
    endTime: '10:20',
    attendees: ['Terry Teng', 'Ryan Kenfield', 'Pride St. Clair', 'Bryan N', 'Sophia J', 'Rhianna Pinkerton'],
    isRecurring: true,
  },
  {
    id: 'ev-004',
    projectId: 'general',
    title: '1:1 Terry × Dana',
    type: '1:1',
    date: TUE,
    startTime: '11:00',
    endTime: '11:30',
    attendees: ['Terry Teng', 'Sophia J'],
    description: 'Weekly producer sync — sprint review, blockers, headcount',
  },
  {
    id: 'ev-005',
    projectId: 'general',
    title: 'All-Hands Monthly',
    type: 'team',
    date: MON,
    startTime: '14:00',
    endTime: '15:00',
    attendees: ['Terry Teng', 'Ryan Kenfield', 'Pride St. Clair', 'Bryan N', 'Daniel Fornell', 'Lauren Palumbo', 'Rhianna Pinkerton', 'Sophia J'],
    description: 'May all-hands: milestone updates, culture, studio news',
  },

  // Last Light
  {
    id: 'ev-010',
    projectId: 'lastlight',
    title: 'Last Light Standup',
    type: 'standup',
    date: MON,
    startTime: '09:00',
    endTime: '09:15',
    attendees: ['Pride St. Clair', 'Bryan N', 'Lauren Palumbo', 'Ryan Kenfield', 'Sophia J'],
    isRecurring: true,
  },
  {
    id: 'ev-011',
    projectId: 'lastlight',
    title: 'Last Light Standup',
    type: 'standup',
    date: WED,
    startTime: '09:00',
    endTime: '09:15',
    attendees: ['Pride St. Clair', 'Bryan N', 'Lauren Palumbo', 'Ryan Kenfield', 'Sophia J'],
    isRecurring: true,
  },
  {
    id: 'ev-012',
    projectId: 'lastlight',
    title: 'Last Light Standup',
    type: 'standup',
    date: FRI,
    startTime: '09:00',
    endTime: '09:15',
    attendees: ['Pride St. Clair', 'Bryan N', 'Lauren Palumbo', 'Ryan Kenfield', 'Sophia J'],
    isRecurring: true,
  },
  {
    id: 'ev-013',
    projectId: 'lastlight',
    title: 'Narrative Review',
    type: 'review',
    date: TUE,
    startTime: '13:00',
    endTime: '14:30',
    attendees: ['Pride St. Clair', 'Lauren Palumbo', 'Terry Teng'],
    description: 'Chapter 3 story review — dialogue pass, pacing notes',
  },
  {
    id: 'ev-014',
    projectId: 'lastlight',
    title: 'Art Direction Sync',
    type: 'sync',
    date: THU,
    startTime: '11:00',
    endTime: '11:45',
    attendees: ['Bryan N', 'Pride St. Clair', 'Ryan Kenfield'],
    description: 'Environment art pass — lighting rigs for Act 2 areas',
  },
  {
    id: 'ev-015',
    projectId: 'lastlight',
    title: 'Playtest Session',
    type: 'playtest',
    date: FRI,
    startTime: '14:00',
    endTime: '16:00',
    attendees: ['Pride St. Clair', 'Lauren Palumbo', 'Rhianna Pinkerton', 'Bryan N'],
    description: 'Internal playtest — puzzle set Alpha 1-3',
  },
  {
    id: 'ev-016',
    projectId: 'lastlight',
    title: '1:1 Jordan × Priya',
    type: '1:1',
    date: MON,
    startTime: '15:00',
    endTime: '15:30',
    attendees: ['Pride St. Clair', 'Lauren Palumbo'],
    description: 'Design–narrative alignment check',
  },

  // Corebound
  {
    id: 'ev-020',
    projectId: 'corebound',
    title: 'Corebound Standup',
    type: 'standup',
    date: MON,
    startTime: '09:30',
    endTime: '09:45',
    attendees: ['Ryan Kenfield', 'Daniel Fornell', 'Pride St. Clair', 'Rhianna Pinkerton', 'Sophia J'],
    isRecurring: true,
  },
  {
    id: 'ev-021',
    projectId: 'corebound',
    title: 'Corebound Standup',
    type: 'standup',
    date: WED,
    startTime: '09:30',
    endTime: '09:45',
    attendees: ['Ryan Kenfield', 'Daniel Fornell', 'Pride St. Clair', 'Rhianna Pinkerton', 'Sophia J'],
    isRecurring: true,
  },
  {
    id: 'ev-022',
    projectId: 'corebound',
    title: 'Corebound Standup',
    type: 'standup',
    date: FRI,
    startTime: '09:30',
    endTime: '09:45',
    attendees: ['Ryan Kenfield', 'Daniel Fornell', 'Pride St. Clair', 'Rhianna Pinkerton', 'Sophia J'],
    isRecurring: true,
  },
  {
    id: 'ev-023',
    projectId: 'corebound',
    title: 'Dungeon Gen Tech Review',
    type: 'review',
    date: TUE,
    startTime: '14:00',
    endTime: '15:30',
    attendees: ['Ryan Kenfield', 'Daniel Fornell', 'Pride St. Clair'],
    description: 'Review procedural dungeon generation v2 — room templates, connector logic',
  },
  {
    id: 'ev-024',
    projectId: 'corebound',
    title: 'Combat Systems Sync',
    type: 'sync',
    date: THU,
    startTime: '13:00',
    endTime: '14:00',
    attendees: ['Ryan Kenfield', 'Daniel Fornell', 'Pride St. Clair', 'Terry Teng'],
    description: 'Combat feel pass — hit stop, camera shake, juice review',
  },
  {
    id: 'ev-025',
    projectId: 'corebound',
    title: '1:1 Terry × Maya',
    type: '1:1',
    date: WED,
    startTime: '15:00',
    endTime: '15:30',
    attendees: ['Terry Teng', 'Ryan Kenfield'],
    description: 'Lead dev check-in — roadmap, team health',
  },
  {
    id: 'ev-026',
    projectId: 'corebound',
    title: 'Playtest — Corebound Demo',
    type: 'playtest',
    date: THU,
    startTime: '15:00',
    endTime: '17:00',
    attendees: ['Ryan Kenfield', 'Daniel Fornell', 'Pride St. Clair', 'Rhianna Pinkerton'],
    description: 'Demo build playtest ahead of publisher meeting',
  },

  // Big Boss Cleanup
  {
    id: 'ev-030',
    projectId: 'bigboss',
    title: 'Big Boss Standup',
    type: 'standup',
    date: TUE,
    startTime: '10:30',
    endTime: '10:45',
    attendees: ['Daniel Fornell', 'Bryan N', 'Rhianna Pinkerton'],
    isRecurring: true,
  },
  {
    id: 'ev-031',
    projectId: 'bigboss',
    title: 'Big Boss Standup',
    type: 'standup',
    date: THU,
    startTime: '10:30',
    endTime: '10:45',
    attendees: ['Daniel Fornell', 'Bryan N', 'Rhianna Pinkerton'],
    isRecurring: true,
  },
  {
    id: 'ev-032',
    projectId: 'bigboss',
    title: 'QA Bug Triage',
    type: 'review',
    date: WED,
    startTime: '11:00',
    endTime: '12:00',
    attendees: ['Rhianna Pinkerton', 'Daniel Fornell', 'Sophia J'],
    description: 'Weekly bug triage — P1/P2 prioritization, patch notes draft',
  },
  {
    id: 'ev-033',
    projectId: 'bigboss',
    title: 'Art Asset Sign-off',
    type: 'sync',
    date: FRI,
    startTime: '11:00',
    endTime: '11:30',
    attendees: ['Bryan N', 'Terry Teng'],
    description: 'Final art sign-off pass before submission build',
  },
]

// ─── Tasks ───────────────────────────────────────────────────────────────────

export const TASKS: Task[] = [
  // General Studio
  {
    id: 'task-001',
    projectId: 'general',
    title: 'Update studio wiki with current project statuses',
    status: 'in-progress',
    priority: 'medium',
    assignee: 'Sophia J',
    dueDate: FRI,
    tags: ['documentation'],
    createdAt: MON,
  },
  {
    id: 'task-002',
    projectId: 'general',
    title: 'Onboard new QA contractor',
    status: 'backlog',
    priority: 'high',
    assignee: 'Terry Teng',
    dueDate: weekDay(7),
    tags: ['hr', 'onboarding'],
    createdAt: MON,
  },
  {
    id: 'task-003',
    projectId: 'general',
    title: 'Renew Unity Pro licenses (3 seats)',
    status: 'backlog',
    priority: 'urgent',
    assignee: 'Sophia J',
    dueDate: TUE,
    tags: ['admin', 'licensing'],
    createdAt: MON,
  },
  {
    id: 'task-004',
    projectId: 'general',
    title: 'Q2 budget reconciliation',
    status: 'review',
    priority: 'high',
    assignee: 'Terry Teng',
    dueDate: FRI,
    tags: ['finance'],
    createdAt: weekDay(-7),
  },
  {
    id: 'task-005',
    projectId: 'general',
    title: 'Set up Figma org workspace for design team',
    status: 'done',
    priority: 'medium',
    assignee: 'Bryan N',
    tags: ['tooling'],
    createdAt: weekDay(-14),
  },
  {
    id: 'task-006',
    projectId: 'general',
    title: 'Draft studio style guide v2',
    status: 'in-progress',
    priority: 'low',
    assignee: 'Bryan N',
    dueDate: weekDay(14),
    tags: ['branding'],
    createdAt: weekDay(-3),
  },

  // Last Light
  {
    id: 'task-010',
    projectId: 'lastlight',
    title: 'Implement Chapter 3 checkpoint system',
    status: 'in-progress',
    priority: 'high',
    assignee: 'Ryan Kenfield',
    dueDate: THU,
    tags: ['programming', 'core'],
    createdAt: weekDay(-5),
  },
  {
    id: 'task-011',
    projectId: 'lastlight',
    title: 'Write dialogue — lighthouse keeper NPC',
    status: 'in-progress',
    priority: 'medium',
    assignee: 'Lauren Palumbo',
    dueDate: WED,
    tags: ['narrative', 'writing'],
    createdAt: weekDay(-3),
  },
  {
    id: 'task-012',
    projectId: 'lastlight',
    title: 'Concept art — ruined observatory',
    status: 'review',
    priority: 'medium',
    assignee: 'Bryan N',
    dueDate: MON,
    tags: ['art', 'concept'],
    createdAt: weekDay(-10),
  },
  {
    id: 'task-013',
    projectId: 'lastlight',
    title: 'Fix torch flicker shader on AMD GPUs',
    status: 'in-progress',
    priority: 'urgent',
    assignee: 'Ryan Kenfield',
    dueDate: TUE,
    tags: ['bug', 'graphics'],
    createdAt: weekDay(-2),
  },
  {
    id: 'task-014',
    projectId: 'lastlight',
    title: 'Design puzzle set Alpha 4-6',
    status: 'backlog',
    priority: 'high',
    assignee: 'Pride St. Clair',
    dueDate: weekDay(10),
    tags: ['design', 'puzzle'],
    createdAt: MON,
  },
  {
    id: 'task-015',
    projectId: 'lastlight',
    title: 'Audio implementation — ambient soundscape Act 2',
    status: 'backlog',
    priority: 'medium',
    assignee: 'Pride St. Clair',
    dueDate: weekDay(12),
    tags: ['audio'],
    createdAt: MON,
  },
  {
    id: 'task-016',
    projectId: 'lastlight',
    title: 'Polish inventory UI animations',
    status: 'done',
    priority: 'low',
    assignee: 'Ryan Kenfield',
    tags: ['ui', 'polish'],
    createdAt: weekDay(-14),
  },
  {
    id: 'task-017',
    projectId: 'lastlight',
    title: 'Update press kit with new screenshots',
    status: 'backlog',
    priority: 'low',
    assignee: 'Sophia J',
    dueDate: weekDay(7),
    tags: ['marketing'],
    createdAt: MON,
  },

  // Corebound
  {
    id: 'task-020',
    projectId: 'corebound',
    title: 'Implement room template system v2',
    status: 'in-progress',
    priority: 'urgent',
    assignee: 'Daniel Fornell',
    dueDate: WED,
    tags: ['programming', 'procedural'],
    createdAt: weekDay(-7),
  },
  {
    id: 'task-021',
    projectId: 'corebound',
    title: 'Balance enemy spawn tables — dungeon floors 1-5',
    status: 'in-progress',
    priority: 'high',
    assignee: 'Pride St. Clair',
    dueDate: THU,
    tags: ['design', 'balance'],
    createdAt: weekDay(-4),
  },
  {
    id: 'task-022',
    projectId: 'corebound',
    title: 'Performance profiling — dungeon gen bottleneck',
    status: 'review',
    priority: 'high',
    assignee: 'Ryan Kenfield',
    dueDate: TUE,
    tags: ['performance', 'programming'],
    createdAt: weekDay(-6),
  },
  {
    id: 'task-023',
    projectId: 'corebound',
    title: 'Art pass — hero character idle animations',
    status: 'backlog',
    priority: 'medium',
    assignee: 'Bryan N',
    dueDate: weekDay(8),
    tags: ['art', 'animation'],
    createdAt: MON,
  },
  {
    id: 'task-024',
    projectId: 'corebound',
    title: 'QA regression on controller input remapping',
    status: 'in-progress',
    priority: 'medium',
    assignee: 'Rhianna Pinkerton',
    dueDate: FRI,
    tags: ['qa', 'input'],
    createdAt: weekDay(-2),
  },
  {
    id: 'task-025',
    projectId: 'corebound',
    title: 'Design loot table — rare drop rates',
    status: 'backlog',
    priority: 'medium',
    assignee: 'Pride St. Clair',
    dueDate: weekDay(9),
    tags: ['design', 'loot'],
    createdAt: MON,
  },
  {
    id: 'task-026',
    projectId: 'corebound',
    title: 'Integrate Steam achievements SDK',
    status: 'backlog',
    priority: 'low',
    assignee: 'Daniel Fornell',
    dueDate: weekDay(21),
    tags: ['programming', 'steam'],
    createdAt: MON,
  },
  {
    id: 'task-027',
    projectId: 'corebound',
    title: 'Fix minimap clipping on ultra-wide aspect ratios',
    status: 'done',
    priority: 'high',
    assignee: 'Daniel Fornell',
    tags: ['bug', 'ui'],
    createdAt: weekDay(-14),
  },

  // Big Boss Cleanup
  {
    id: 'task-030',
    projectId: 'bigboss',
    title: 'Fix crash on Stage 4 death sequence',
    status: 'in-progress',
    priority: 'urgent',
    assignee: 'Daniel Fornell',
    dueDate: TUE,
    tags: ['bug', 'crash'],
    createdAt: weekDay(-3),
  },
  {
    id: 'task-031',
    projectId: 'bigboss',
    title: 'Texture compression pass — PS5 build',
    status: 'in-progress',
    priority: 'high',
    assignee: 'Bryan N',
    dueDate: WED,
    tags: ['art', 'optimization'],
    createdAt: weekDay(-5),
  },
  {
    id: 'task-032',
    projectId: 'bigboss',
    title: 'Write submission checklist for platform cert',
    status: 'review',
    priority: 'urgent',
    assignee: 'Rhianna Pinkerton',
    dueDate: MON,
    tags: ['qa', 'submission'],
    createdAt: weekDay(-7),
  },
  {
    id: 'task-033',
    projectId: 'bigboss',
    title: 'Final localization review — JP/KR strings',
    status: 'backlog',
    priority: 'high',
    assignee: 'Sophia J',
    dueDate: weekDay(5),
    tags: ['localization'],
    createdAt: MON,
  },
  {
    id: 'task-034',
    projectId: 'bigboss',
    title: 'Patch notes draft — v1.4.0',
    status: 'in-progress',
    priority: 'medium',
    assignee: 'Sophia J',
    dueDate: THU,
    tags: ['documentation'],
    createdAt: weekDay(-2),
  },
  {
    id: 'task-035',
    projectId: 'bigboss',
    title: 'Regressed audio bug — boss music cuts out',
    status: 'backlog',
    priority: 'high',
    assignee: 'Daniel Fornell',
    dueDate: FRI,
    tags: ['bug', 'audio'],
    createdAt: TUE,
  },
  {
    id: 'task-036',
    projectId: 'bigboss',
    title: 'Verify save migration from v1.2 → v1.4',
    status: 'done',
    priority: 'urgent',
    assignee: 'Rhianna Pinkerton',
    tags: ['qa', 'save-system'],
    createdAt: weekDay(-10),
  },
]

// Helper: get team members for a project
export function getProjectMembers(projectId: ProjectId): TeamMember[] {
  return TEAM_MEMBERS.filter((m) => m.projects.includes(projectId))
}

// Helper: get events for a project (optionally filtered by date)
export function getProjectEvents(projectId: ProjectId, dateFilter?: string): CalendarEvent[] {
  return CALENDAR_EVENTS.filter(
    (e) => e.projectId === projectId && (!dateFilter || e.date === dateFilter)
  )
}

// Helper: get tasks for a project, optionally by status
export function getProjectTasks(projectId: ProjectId, status?: string): Task[] {
  return TASKS.filter(
    (t) => t.projectId === projectId && (!status || t.status === status)
  )
}
